feat: track number of CLI installations [FTL-8744]
affinidi/affinidi-cli pull request #135
Opened 2023-01-23 16:17 UTC by YoussefAWasfy

2023-01-26 16:42 UTC, dendavidov-affinidi commented on package.json
> +    "postinstall": "sh \"bin/postinstall\""
not cross-platform

2023-01-26 16:43 UTC, dendavidov-affinidi commented on bin/postinstall
> +code=$(curl --write-out "%{http_code}\n" --location -X POST 'https://analytics-stream.prod.affinity-project.org/api/events' \
what if there is no curl?

2023-01-26 16:44 UTC, dendavidov-affinidi requested changes
This solution is not cross-platform.
I'd recommend to use js file instead of bash
example:
https://github.com/zloirock/core-js/blob/master/packages/core-js/package.json#L68

2023-01-27 10:29 UTC, JonasEtzold approved these changes
LGTM

2023-01-27 10:39 UTC, merged

2023-01-27 14:16 UTC, JonasEtzold commented
:tada: This PR is included in version 1.55.0 :tada:

The release is available on:
- [GitHub release](https://github.com/affinidi/affinidi-cli/releases/tag/v1.55.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@affinidi/cli/v/1.55.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: